# 机器人基本配置
bot:
  websocket: "ws://127.0.0.1:6700"  # OneBot WebSocket地址
  accessToken: ""  # 访问令牌（如果有）

# 定时任务配置
scheduledTasks:
  - name: "早安问候"  # 任务名称
    type: "SEND_MESSAGE"  # 任务类型
    targetType: "GROUP"  # 目标类型：GROUP或PRIVATE
    targetId: 123456789  # 群号或QQ号
    cronExpression: "0 30 7 * * ?"  # 每天早上7:30执行
    content: "早上好，今天也要元气满满哦！"  # 发送的消息内容
    
  - name: "晚间提醒"
    type: "SEND_MESSAGE"
    targetType: "PRIVATE"
    targetId: 987654321
    cronExpression: "0 0 22 * * ?"  # 每天晚上10点执行
    content: "该休息了，记得早点睡觉哦~"
    
  - name: "周末全体禁言"
    type: "GROUP_BAN_ALL"
    targetType: "GROUP"
    targetId: 123456789
    cronExpression: "0 0 23 ? * FRI"  # 每周五晚上11点执行
    enable: true  # true表示开启全体禁言，false表示关闭
    
  - name: "周一解除全体禁言"
    type: "GROUP_BAN_ALL"
    targetType: "GROUP"
    targetId: 123456789
    cronExpression: "0 0 8 ? * MON"  # 每周一早上8点执行
    enable: false  # false表示关闭全体禁言
    
  - name: "特定用户禁言"
    type: "GROUP_BAN_MEMBER"
    targetType: "GROUP"
    targetId: 123456789
    memberId: 111222333  # 要禁言的成员QQ号
    cronExpression: "0 0 12 * * ?"  # 每天中午12点执行
    duration: 3600  # 禁言时长（秒），0表示解除禁言