name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: scheduler-bot
        path: target/scheduler-bot-1.2.2.jar
    
    - name: Prepare release files
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p release
        cp target/scheduler-bot-1.2.2.jar release/
        cp start.bat release/
        cp start.sh release/
        cp README.md release/
        cp LICENSE release/
        chmod +x release/start.sh
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/scheduler-bot-1.2.2.jar
          release/start.bat
          release/start.sh
          release/README.md
          release/LICENSE
        draft: false
        prerelease: false
        generate_release_notes: true 